In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5], dtype = float)
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [8]:
# 1 DIMENTION
print(arr1.shape)
print(arr1.ndim)

(5,)
1


In [11]:
# 0 DIMENTION
arr0 = np.array(12)
print(arr0.shape)
arr0.ndim

()


0

In [12]:
# 2 DIMENTION
arr2 = np.array([[1,2], [5,6]])
print(arr2.shape)
print(arr2.ndim)

(2, 2)
2


In [13]:
# 3 Dimention
a3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(a3.shape)
print(a3.ndim)

(2, 2, 3)
3


In [17]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
np.eye(3, 3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
np.eye(3, 3, dtype = int, k = -1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [22]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([7,8,9])
print(a+b)

[[ 8 10 12]
 [11 13 15]]


In [28]:
np.zeros((3,2), dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [30]:
np.full((3,2), 7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [35]:
# MATHEMATICAL METHODS THROUGH NUMPY
arr = np.array([1,2,3,4,5])
print(f'Sum of all elements of array: {np.sum(arr)}')
print(f'Mean of all elements of array: {np.mean(arr)}')
print(f'Median of all elements of array: {np.median(arr)}')
print(f'Standard deviation of all elements of array: {np.std(arr)}')
print(f'Variance of all elements of array: {np.var(arr)}')
print(f'Minimum of all elements of array: {np.min(arr)}')
print(f'Maximum of all elements of array: {np.max(arr)}')
print(f'Product of all elements of array: {np.prod(arr)}')

Sum of all elements of array: 15
Mean of all elements of array: 3.0
Median of all elements of array: 3.0
Standard deviation of all elements of array: 1.4142135623730951
Variance of all elements of array: 2.0
Minimum of all elements of array: 1
Maximum of all elements of array: 5
Product of all elements of array: 120


In [36]:
np.random.randint(1,10,size=(2,3))

array([[3, 5, 8],
       [7, 6, 8]])

In [38]:
np.random.rand((3))

array([0.86173676, 0.29491689, 0.84955394])

In [37]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
arr

array([1, 5, 3, 2, 4])

In [39]:
x = np.array([1,2])
y = np.array([3,4])
print(np.transpose((x, y)))
print(np.column_stack((x,y)))
print(np.row_stack((x,y)))
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[1 2 3 4]


/tmp/ipython-input-3049242384.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((x,y)))


In [45]:
arr = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])

print(arr[1,1])
print(arr[0,2])
print(arr[2,:3])
print(arr[:, 2])

50
30
[70 80 90]
[30 60 90]


In [47]:
arr = np.array([20,30,40,50])
result = np.where(arr>25, 'High', 'Low')
print(result)

['Low' 'High' 'High' 'High']


In [48]:
a = np.array([1,2,3])
b = a.copy()
c = a.view()
a[0] = 150
print(a)
print(b)
print(c)

[150   2   3]
[1 2 3]
[150   2   3]
